#platform
platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'NTESLiveDetectPublicDemo' do
pod 'Masonry', '~> 1.0.2' 
pod 'WHToast'
pod 'NTESLiveDetect', '3.0.1'
pod 'AFNetworking'

end
